spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/rental_test?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: minnan.site
    port: 6379
    database: 1
    password: minnan
server:
  port: 8108

jwt:
  route:
    authentication:
      path: /rental/auth/login/password
  header: Authorization
  expiration: 604800
  scret: min107

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

logging:
  file:
    name: ./logs/rental-config/rental-config.log