POST {{authUrl}}/rental/auth/login/password
Content-Type: application/json

{
  "username": "min",
  "password": "c663b11dff4be0badcf652212a2c1102"
}


> {% client.global.set("admin_token", response.body.data.token); %}

###
POST {{authUrl}}/rental/auth/login/password
Content-Type: application/json

{
  "username": "18925503712",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

> {% client.global.set("landlord_token", response.body.data.token); %}

###
POST {{authUrl}}/rental/auth/login/password
Content-Type: application/json

{
  "username": "13813812138",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

> {% client.global.set("tenant_token", response.body.data.token) %}

###
POST {{userUrl}}/rental/user/getUserList
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{userUrl}}/rental/user/addUser/tenant
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "username": "13813812138",
  "password": "e10adc3949ba59abbe56e057f20f883e",
  "realName": "英"
}

###
POST {{userUrl}}/rental/user/updateUser
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "id": 12,
  "realName": "王五",
  "phone": "17328483960"
}

###
POST {{userUrl}}/rental/user/disableUser
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "id": 6
}

###
POST {{userUrl}}/rental/user/enableUser
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "id": 6
}

###
POST {{houseUrl}}/rental/house/addHouse
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "address": "永和街1号",
  "directorName": "李四",
  "directorPhone": "17238390012"
}

###
POST {{houseUrl}}/rental/house/getHouseList
Content-Type: application/json
Authorization: Bearer {{landlord_token}}

{
  "pageSize": 10,
  "pageIndex": 1
}

###
POST {{configUrl}}/rental/common/addMenu
Content-Type:application/json
Authorization: Bearer {{admin_token}}

{
  "name": "日志",
  "url": "/logs",
  "icon": "glyphicon glyphicon-file",
  "role": "ADMIN"
}

###
POST http://localhost:2000/rental/common/getMenu
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{}

###
POST {{houseUrl}}/rental/house/getHouseInfo
Content-Type: application/json
Authorization: Bearer {{landlord_token}}

{
  "id": 6
}

###
POST {{houseUrl}}/rental/house/updateHouse
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "id": 6,
  "directorName": "路人甲",
  "directorPhone": "13813812133"
}