spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/rental_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: minnan.site
    port: 6379
    database: 1
    password: minnan

server:
  port: 8105

jwt:
  header: Authorization
  expiration: 604800
  scret: min107

logging:
  file:
    name: ./logs/rental_bill/rental-bill.log

dubbo:
  application:
    name: rental-bill
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20884

mybatis-plus:
  mapper-locations: /site/minnan/rental/domain/mapper/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  bucketName: link-server
  baseUrl: http://minnan.site:2000