spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/rental_test?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: minnan.site
    port: 6379
    database: 5
    password: minnan

server:
  port: 8101

jwt:
  header: Authorization
  expiration: 604800
  scret: min107