spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/rental_test?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  redis:
    host: minnan.site
    port: 6379
    database: 1
    password: minnan

server:
  port: 8101

jwt:
  header: Authorization
  expiration: 604800
  scret: min107

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

logging:
  file:
    name: ./logs/rental-house/rental-house.log